### ISSUE TITLE
How should I use downloaded LD matrix?

### ISSUE THREAD

**Issue by yingji15** [YinLiLin/hibayes#10]
Hi there,

Thanks for making this available!
I am wondering if I can use LD matrix downloaded from (https://zenodo.org/record/3350914#.X94SHOn0lBx ) instead of computing by myself. For example, can I specify the path to this LD matrices and run SBayesR using hibayes package?

`ldm1 = read("xx") # path to downloaded LD matrix`
`fit = sbayes(sumstat=sumstat, ldm=ldm1, model="SBayesR", niter=20000, nburn=10000, outfreq=10, verbose=TRUE)`

Thanks!

Ying

**Comment by YinLiLin** [comment]
Hi Ying,

Thank you for trying hibayes.
Sorry that hibayes could not use the LD matrix computed by GCTB, as hibayes uses different types of LD matrix. I just wondering why not use GCTB directly? 

Best,
Lilin

**Comment by yingji15** [comment]
Hi Lilin,
Thank you so much for your reply! Yes I initially I tried the latest version of GCTB (2.02) but it didn't work in my current environment. So I was looking for other implementations online. I found GCTB (2.0) works in my environment. Thank you so much!

Best,
Ying
