### ISSUE TITLE
saving standard errors of variance components and heritability

### ISSUE THREAD

**Issue by Siavash-cloud** [YinLiLin/hibayes#17]
Hello,
I know that your package report standard errors of variance components and heritability in log or console of R studio.
So, I wonder how can I get or save standard errors of variance components and heritability as an output for example in a data frame or a table? 

Regards,
Siavash

**Comment by YinLiLin** [comment]
Hi Siavash,

Thank you for using hibayes.
The latest version on both CRAN and GitHub has returned the sampled values for all unknown parameters, it can be accessed from the list ```$MCMCsamples```,  the standard deviation of all estimated unknown parameters ('p') can be obtained by the function ```apply(fit$MCMCsamples$p, 1, sd)```.

Best,
Lilin

**Comment by Siavash-cloud** [comment]
Thanks! it works
