### ISSUE TITLE
The predictive accuracies of cor of prediction and ture values are  different between two R packages

### ISSUE THREAD

**Issue by Xinin-loveScience** [YinLiLin/hibayes#8]
Hello! 
The packages "hibayes" and "G2P" were performed to GS of weight trait, and the predictive accuracies were significantly different. The accuracies were 0.82 and 0.15 by BayesB in hibayes and G2P, respectively. I don't know the reasons.

**Comment by YinLiLin** [comment]
Hi,

Thank you for using hibayes.
I am not familiar with G2P package you mentioned, I suggest to try BGLR package to fit Bayes model if you want to make a comparison.

LL

**Comment by Xinin-loveScience** [comment]
Hi, 
Thanks for your reply.
Do you call the BGLR package? I use the G2P is called BGLR package to calculate bayes.

**Comment by YinLiLin** [comment]
I just quickly searched the G2P package, it seems to be a tool enriched with lots of models for genomic selection by integrating some widely-used packages. Except for BGLR, you can also try [GCTB](https://cnsgenomics.com/software/gctb/#Bayesianalphabet) to fit varies Bayes models for a comparison.

**Comment by Xinin-loveScience** [comment]
谢谢，我用了你说的这个GCTB做了BayesB，但是输出文件没有发现育种值？

**Comment by YinLiLin** [comment]
GCTB只输出标记效应值，需要结合plink计算个体育种值

**Comment by Xinin-loveScience** [comment]
谢谢，有具体的plink计算育种值的方法吗？

**Comment by YinLiLin** [comment]
请参考plink --score功能
